### ISSUE TITLE
Updating the default README Example

### ISSUE THREAD

**Issue by ahuang11** [AlessandroLollo/prefect-transform#1]
Thanks for expanding the Prefect ecosystem!

I noticed the example on the README is still the default example. Perhaps that can be updated to reflect how to use "create_materialization"

**Comment by AlessandroLollo** [comment]
Hey @ahuang11 👋 
Thanks for catching this!
I will release a new version with an updated README.

**Comment by AlessandroLollo** [comment]
New version released!
Let me know if it looks good to you (I'll close the issue then).

**Comment by AlessandroLollo** [comment]
README has been updated.
Closing this issue.
